### ISSUE TITLE
InflateException

### ISSUE THREAD

**Issue by fillky** [inazaruk/map-fragment#3]
Sorry, 
I am new in android but I have this problem when I tried to implement your solution. I always get this errors and I cant google any right solutions.

11-24 01:46:29.183: ERROR/AndroidRuntime(379): FATAL EXCEPTION: main
        java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sito/com.sito.map.GoogleMapActivity}: android.view.InflateException: Binary XML file line #12: Error inflating class <unknown>
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1647)
        at android.app.ActivityThread.startActivityNow(ActivityThread.java:1487)
        at android.app.LocalActivityManager.moveToState(LocalActivityManager.java:127)
        at android.app.LocalActivityManager.startActivity(LocalActivityManager.java:339)
        at com.sito.map.ActivityHostFragment.onCreateView(ActivityHostFragment.java:22)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:1460)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:911)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1088)
        at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1444)
        at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:461)
        at com.sito.MainActivity$TabManager.onTabChanged(MainActivity.java:189)
        at android.widget.TabHost.invokeOnTabChangeListener(TabHost.java:359)
        at android.widget.TabHost.setCurrentTab(TabHost.java:344)
        at android.widget.TabHost$2.onTabSelectionChanged(TabHost.java:132)
        at android.widget.TabWidget$TabClickListener.onClick(TabWidget.java:456)
        at android.view.View.performClick(View.java:2485)
        at android.view.View$PerformClick.run(View.java:9080)
        at android.os.Handler.handleCallback(Handler.java:587)
        at android.os.Handler.dispatchMessage(Handler.java:92)
        at android.os.Looper.loop(Looper.java:130)
        at android.app.ActivityThread.main(ActivityThread.java:3683)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:507)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
        at dalvik.system.NativeStart.main(Native Method)
        Caused by: android.view.InflateException: Binary XML file line #12: Error inflating class <unknown>
        at android.view.LayoutInflater.createView(LayoutInflater.java:518)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:570)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:623)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:408)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:320)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:276)
        at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:207)
        at android.app.Activity.setContentView(Activity.java:1657)
        at com.sito.map.GoogleMapActivity.onCreate(GoogleMapActivity.java:25)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1611)
        ... 26 more
        Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.constructNative(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:415)
        at android.view.LayoutInflater.createView(LayoutInflater.java:505)
        ... 36 more
        Caused by: java.lang.IllegalStateException: You are only allowed to have a single MapView in a MapActivity
        at com.google.android.maps.MapActivity.setupMapView(MapActivity.java:397)
        at com.google.android.maps.MapView.<init>(MapView.java:289)
        at com.google.android.maps.MapView.<init>(MapView.java:264)
        at com.google.android.maps.MapView.<init>(MapView.java:247)
        ... 39 more

**Comment by inazaruk** [comment]
Take a look at: "You are only allowed to have a single MapView in a MapActivity". This is most likely issue with your activity.

Do next:
a) Try to reproduce the issue without using fragments. In other words, try launching MapActivity directly. If you see the same issue, it's something you did wrong with MapActivity (and not with fragments adoption).
b) If a. doesn't help, try to create a small sample project and repro the issue. Post link to this code here so I (or somebody else) can look into it.
